services:
  nginx:
    image: kiri909/rrrcn-web:latest
    build:
      dockerfile: .Dockerfile
    ports:
      - "9999:80"
    volumes:
  #        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
