import { UsersPermissions_Role } from "./UsersPermissions_Role";
import { Result } from "./Result";
import { AuthExt_AuthProvider } from "./AuthExt_AuthProvider";
export type UsersPermissions_User = {
  id: number;
  username: string;
  email: string;
  provider: string | null;
  password: string | null;
  resetPasswordToken: string | null;
  confirmationToken: string | null;
  confirmed: boolean | null;
  blocked: boolean | null;
  role: UsersPermissions_Role | null;
  results: Result[] | null;
  createdAt: string | null;
  updatedAt: string | null;
  createdBy: any | null;
  updatedBy: any | null;
  auth_steps_number: number | null;
  auth_providers: AuthExt_AuthProvider[] | null;
};
