services:
  api:
    environment:
      R_BASE_URL: "http://R:8000"
    image: kiri909/rrrcn-api:latest
    build:
      dockerfile: ./packages/admin/Dockerfile
      context: ../..
    ports:
      - "1337:1337"
    volumes:
      - strapi_database:/app/packages/admin/.tmp
      - strapi_public:/app/packages/admin/public
  R:
    image: kiri909/rrrcn-r-api:latest
    build:
      dockerfile: ./Dockerfile
      context: ../r-api
    ports:
      - "8000:8000"
    volumes:
      - strapi_public:/app/api/public
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
    - pgdata:/var/lib/postgresql/data/pgdata

volumes:
  pgdata: rrrcn_pgdata
  strapi_database:
    external: ${STRAPI_USE_EXTERNAL_DB:-false}
  strapi_public:
    external: ${STRAPI_USE_EXTERNAL_PUBLIC:-false}
