services:
  api:
    environment:
      R_BASE_URL: "http://R:8000"
    image: kiri909/rrrcn-api:0.0.5
    ports:
      - "1337:1337"
    volumes:
      - ./.tmp:/app/packages/admin/.tmp
      - ./public:/app/packages/admin/public
  R:
    image: kiri909/rrrcn-r-api:0.0.3
    ports:
      - "8000:8000"
    volumes:
      - ./public:/app/api/public
