on:
#  push:
#   branches:
#    - main
  workflow_dispatch:
    inputs:
      staging:
        description: 'Staging'
        required: true
        default: 'develop'
        type: choice
        options:
          - "develop"
          - "production"
jobs:
   # build_admin: 
   deploy_admin:
     runs-on: [self-hosted, "${{ inputs.staging }}"]
     steps:
       - name: Checkout
         uses: actions/checkout@v4
         with:
           submodules: true
       - name: docker-compose
         run: docker compose -p rrrcn-backend-${{inputs.staging}} up -f ./packages/admin/docker-compose.yml
           
