on:
  push:
    branches:
     - monorepo/develop
    env:
      GITHUB_ACTION_STAGING: develop
  workflow_dispatch:
    inputs:
      staging:
        description: 'Staging'
        required: true
        default: 'develop'
        type: choice
        options:
          - "develop"
          - "production"
    env:
      GITHUB_ACTION_STAGING: ${{inputs.staging}}
jobs:
   build_admin:
     environment: $GITHUB_ACTION_STAGING
     runs-on: [self-hosted, build]
     steps:
       - name: Checkout
         uses: actions/checkout@v4
         with:
           submodules: true
       - name: Build
         run: docker compose build
       - name: Build
         run: docker compose push


   deploy_admin:
     runs-on: [self-hosted, $GITHUB_ACTION_STAGING]
     environment: $GITHUB_ACTION_STAGING
     steps:
       - name: Checkout
         uses: actions/checkout@v4
         with:
           submodules: true
       - name: docker-compose
         run: docker compose -p rrrcn-backend-${GITHUB_ACTION_STAGING} -f ./packages/admin/docker-compose.yml up

